# This is a basic workflow to help you get started with Actions
name: roxygen
on: [push]
jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: List files
        run: |
          DES=$(sed -n -e 's/Package: //p' DESCRIPTION)_$(sed -n -e 's/Version: //p' DESCRIPTION).tar.gz
          echo $DES
          curl --request POST \
            --url "https://api.github.com/repos/csgillespie/test/releases" \
            --header "authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            --data '{"tag_name=test"}'


