# This is a basic workflow to help you get started with Actions
name: roxygen
on: [push]
jobs:
  example:
    runs-on: alpine
    steps:
      - uses: actions/checkout@v1
      - name: List files
        run: |
          DES=$(sed -n -e 's/Package: //p' DESCRIPTION)_$(sed -n -e 's/Version: //p' DESCRIPTION).tar.gz
          echo $DES
          curl --user csgillespie --header "Accept: application/vnd.github.manifold-preview" --data "tag_name=test"  "https://api.github.com/repos/csgillespie/test/releases"

