# This is a basic workflow to help you get started with Actions
name: roxygen
on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1

      - name: setup
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git config --global push.default simple
     
      - name: Dependences
        run: |
          remotes::install_deps(dependencies = TRUE)
          install.packages(c("drat", "cli"))
        shell: Rscript {0}
      - name: build    
        run: R CMD build .
 
      - name: drat
        run: |
          ## Get drat repo
          cp test_0.1.0.tar.gz ../
          cd .. && cd drat
          git remote add upstream "https://${{ secrets.GITHUB_TOKEN }}@github.com/csgillespie/drat.git"
          git fetch --depth 1 upstream
          # Rscript -e "file.remove('err.txt')"
          git checkout gh-pages
          Rscript -e "drat::insertPackage('../test_0.1.0.tar.gz', repodir = '.', \
                        commit = 'GH Action')"

          Rscript -e "cli::cli_alert_info('Pushing to drat')"
          git push
          cd ..
          Rscript -e "cli::cli_alert_success('All done')"
